
name: Quang2107

on: workflow_dispatch

jobs:

  build:

    runs-on: windows-latest

    timeout-day: 30

    steps:

    - name: Đang Tải NGROK!

      run: |

        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

        Invoke-WebRequest https://raw.githubusercontent.com/TuanAnhITT/DC/master/start.bat -OutFile start.bat

        Invoke-WebRequest https://raw.githubusercontent.com/TuanAnhITT/DC/master/wallpaper.png -OutFile wallpaper.png

        Invoke-WebRequest https://raw.githubusercontent.com/TuanAnhITT/DC/master/wallpaper.bat -OutFile wallpaper.bat

        Invoke-WebRequest https://raw.githubusercontent.com/TuanAnhITT/DC/master/loop.bat -OutFile loop.bat

    - name: Đang Tải Launcher!

      run: |

        Invoke-WebRequest https://raw.githubusercontent.com/TuanAnhITT/DC/master/launcher/kiemthanh.exe -OutFile kiemthanh.exe

    - name: Đang Giải Nén Ngrok File...

      run: Expand-Archive ngrok.zip

    - name: Đang Kết Nối Đến Ngrok!

      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      env:

        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Đang Xác Thực..

      run: | 

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Đang Bật...

      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'

    - name: Đang Kết Nối Đến Máy Chủ...

      run: cmd /c start.bat

    - name: Đã Tạo VPS Thành Công!

      run: cmd /c loop.bat

