name: Hacker-Vps

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: checkout Hacker-Vps
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization Hacker-Vps
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GHUSER }}
           git config --global user.email ${{ secrets.GHMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GHUSER }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning Repository
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GHUSER }}/${{ secrets.REPO }} hacker
       - name: running Hacker-Vps
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd hacker
           docker build . -t hacker
           docker run hacker
       - name: loop Hacker-Vps
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Hacker-Vps : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:hacker-vps
